# Generated by Django 4.2.2 on 2023-06-08 06:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbonReestr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dev_name", models.TextField(max_length=200)),
                ("ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("dev_model", models.TextField(max_length=200)),
                ("vendor", models.TextField(max_length=200)),
                ("role", models.TextField(max_length=200)),
                ("num_of_ports", models.IntegerField()),
                ("geo_address", models.TextField(max_length=200)),
            ],
            options={
                "verbose_name": "Абонентский Реестр",
                "verbose_name_plural": "Абонентский Реестр",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ASOCatalog",
            fields=[
                (
                    "nomenclature_num",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Номенклатурный номер",
                    ),
                ),
                ("product_name", models.TextField(verbose_name="Наименование товара")),
                (
                    "unit_of_measure",
                    models.CharField(max_length=255, verbose_name="Единицы измерения"),
                ),
                (
                    "cuantity",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price_wo_nds",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена за единицу без НДС, $",
                    ),
                ),
                (
                    "agency_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Агентское вознаграждение, %",
                    ),
                ),
            ],
            options={
                "verbose_name": "АСО каталог",
                "verbose_name_plural": "АСО каталог",
                "ordering": ("product_name",),
            },
        ),
    ]
