# Generated by Django 4.2.2 on 2023-06-09 11:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbonReestr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dev_name", models.TextField(max_length=200)),
                ("ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("dev_model", models.TextField(max_length=200)),
                ("vendor", models.TextField(max_length=200)),
                ("role", models.TextField(max_length=200)),
                ("num_of_ports", models.IntegerField()),
                ("geo_address", models.TextField(max_length=200)),
            ],
            options={
                "verbose_name": "Абонентский Реестр",
                "verbose_name_plural": "Абонентский Реестр",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ASOCatalog",
            fields=[
                (
                    "nomenclature_num",
                    models.PositiveBigIntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Номенклатурный номер",
                    ),
                ),
                ("product_name", models.TextField(verbose_name="Наименование товара")),
                (
                    "unit_of_measure",
                    models.CharField(max_length=255, verbose_name="Единицы измерения"),
                ),
                (
                    "cuantity",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price_wo_nds",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена за единицу без НДС, $",
                    ),
                ),
                (
                    "agency_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Агентское вознаграждение, %",
                    ),
                ),
            ],
            options={
                "verbose_name": "АСО",
                "verbose_name_plural": "АСО",
                "ordering": ["product_name"],
            },
        ),
        migrations.CreateModel(
            name="OneTimeWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.TextField(
                        max_length=255, verbose_name="Наименование операционной услуги"
                    ),
                ),
                (
                    "expert",
                    models.TextField(max_length=255, verbose_name="Тип экспертизы"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Ставка без НДС, руб.",
                    ),
                ),
                ("hours", models.SmallIntegerField(verbose_name="Трудозатраты")),
                (
                    "incontract",
                    models.CharField(
                        blank=True,
                        choices=[("In contract", "IN"), ("Not in contract", "NEW")],
                        max_length=255,
                        verbose_name="В рамках контракта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разовые работа",
                "verbose_name_plural": "Разовые работы",
                "ordering": ("service_name",),
            },
        ),
        migrations.CreateModel(
            name="UserOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_code",
                    models.TextField(
                        max_length=50, verbose_name="Код операционной услуги"
                    ),
                ),
                (
                    "service_name",
                    models.TextField(
                        max_length=255, verbose_name="Наименование операционной услуги"
                    ),
                ),
                (
                    "geo_address",
                    models.TextField(max_length=255, verbose_name="Адрес площадки"),
                ),
                (
                    "aso",
                    models.TextField(max_length=255, verbose_name="Тип оборудования"),
                ),
                (
                    "one_time_operations",
                    models.TextField(max_length=255, verbose_name="Разовые работы"),
                ),
            ],
        ),
    ]
