# Generated by Django 4.2.2 on 2023-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtk_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimework",
            name="incontract",
            field=models.CharField(
                blank=True,
                choices=[("IN", "In contract"), ("NEW", "Not in contract")],
                max_length=255,
                verbose_name="В рамках контракта",
            ),
        ),
    ]
