# Generated by Django 4.2.2 on 2023-06-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtk_app", "0002_alter_onetimework_incontract"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onetimework",
            options={
                "ordering": ("service_name",),
                "verbose_name": "Разовая работа",
                "verbose_name_plural": "Разовые работы",
            },
        ),
    ]
